CREATE DATABASE db_product;

INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Sport Sneakers', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg', '599.00', 'High-performance sport sneakers designed for optimal comfort and style.', 'Footwear', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Gift Bag', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-2.jpg', '99.00', 'Elegant gift bag suitable for various occasions with a unique and stylish design.', 'Accessories', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Smart Watch', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-4.jpg', '249.97', 'Advanced smartwatch with fitness tracking, heart rate monitoring, and smart notifications.', 'Electronics', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Plant Shelves', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-3.jpg', '249.97', 'Stylish and functional plant shelves for displaying your favorite plants at home.', 'Home Decor', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Running Shoes', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-5.jpg', '199.49', 'Lightweight and durable running shoes engineered for maximum performance.', 'Footwear', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Sun Block', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-6.jpg', '17.19', 'Effective sunblock with SPF 50 for protecting your skin from harmful UV rays.', 'Beauty', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Light Spot', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-8.jpg', '149.49', 'Contemporary light spot designed to illuminate and enhance your living space.', 'Home Decor', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Travel Bag', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-9.jpg', '5.00', 'Compact and lightweight travel bag for convenient and organized travel.', 'Travel Accessories', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('X-Box Controller', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-10.jpg', '99.49', 'Gaming controller compatible with X-Box for an immersive gaming experience.', 'Electronics', '2024-01-01', '2024-01-01');
INSERT INTO `db_product`.`products` (`name`, `photo`, `price`, `description`, `type`, `createdAt`, `updatedAt`) VALUES ('Leather Backpack', 'https://flowbite.s3.amazonaws.com/docs/gallery/square/image-11.jpg', '399.49', 'Premium leather backpack with multiple compartments for modern and stylish travel.', 'Fashion', '2024-01-01', '2024-01-01');

SELECT * FROM db_product.products;

USE db_product;